language: node_js

cache:
  directories:
    - node_modules
    - ~/.npm

node_js:
  -'12'

git:
  depth: 3

script:
  - yarn build

deploy:
  provider: pages
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  target_branch: gh-pages
  commit_message: "update deploy travis run..."
  on:
    branch: master